# Configuration file for terminalizer
# See https://github.com/faressoft/terminalizer for all available options

# Record
command: bash -l
cwd: null
env:
  recording: true
cols: 80
rows: 24

# Delays
frameDelay: auto
maxIdleTime: 2000

# GIF
quality: 100
repeat: 0

# Terminal
cursorStyle: block
fontFamily: 'Monaco, Lucida Console, Ubuntu Mono, monospace'
fontSize: 12
lineHeight: 1.4
letterSpacing: 0

# Theme
theme:
  background: 'transparent'
  foreground: '#d0d0d0'
  cursor: '#ffffff'
  black: '#000000'
  red: '#ff5555'
  green: '#50fa7b'
  yellow: '#f1fa8c'
  blue: '#bd93f9'
  magenta: '#ff79c6'
  cyan: '#8be9fd'
  white: '#bfbfbf'
  brightBlack: '#4d4d4d'
  brightRed: '#ff6e67'
  brightGreen: '#5af78e'
  brightYellow: '#f4f99d'
  brightBlue: '#caa9fa'
  brightMagenta: '#ff92d0'
  brightCyan: '#9aedfe'
  brightWhite: '#e6e6e6'

# Watermark (disabled for cleaner demos)
watermark:
  imagePath: null
  style:
    position: absolute
    right: 15px
    bottom: 15px
    width: 100px
    opacity: 0.9

# Frame box (window style for professional look)
frameBox:
  type: window
  title: inquirerjs-checkbox-search
  style:
    boxShadow: 0 5px 10px rgba(0, 0, 0, 0.4)
    margin: 20px 