name: Header Demo GIF

on:
  pull_request:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'demos/**'
      - 'src/**'
      - '.github/workflows/generate-header-demo.yml'
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'demos/**'
      - 'src/**'
      - '.github/workflows/generate-header-demo.yml'
  workflow_dispatch:
    inputs:
      header_example:
        description: 'Which example to use as header.gif'
        required: false
        default: 'basic'
        type: choice
        options:
          - 'basic'
          # Add more as tape files are created
      commit_updates:
        description: 'Commit updates back to branch?'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-demo-gif
  cancel-in-progress: true

jobs:
  generate-header-demo:
    name: 'Generate'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine release-please context
        id: context
        run: |
          # Check commit message for release-please pattern (works for both PRs and commits)
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            commit_message="${{ github.event.pull_request.title }}"
            echo "is_pr=true" >> $GITHUB_OUTPUT
          else
            commit_message="${{ github.event.head_commit.message }}"
            echo "is_pr=false" >> $GITHUB_OUTPUT
          fi

          if [[ "$commit_message" =~ ^chore\(main\): ]]; then
            echo "is_release_please=true" >> $GITHUB_OUTPUT
            echo "🔍 Release-please detected: $commit_message"
          else
            echo "is_release_please=false" >> $GITHUB_OUTPUT
            echo "🔍 Regular change detected: $commit_message"
          fi

      - name: Determine header example
        id: header
        run: |
          # Use input parameter if provided (workflow_dispatch), otherwise default to 'basic'
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            HEADER_EXAMPLE="${{ github.event.inputs.header_example }}"
          else
            HEADER_EXAMPLE="basic"
          fi

          echo "example=$HEADER_EXAMPLE" >> $GITHUB_OUTPUT
          echo "🎯 Will generate '$HEADER_EXAMPLE' demo as header.gif"

      - name: Generate demo GIF
        run: |
          # Set deterministic timestamp for consistent builds
          export SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)

          # Generate the chosen example
          EXAMPLE="${{ steps.header.outputs.example }}"
          echo "🎬 Generating demo for: $EXAMPLE"
          npm run "demo:generate:$EXAMPLE"

      - name: Create header GIF from demo
        run: |
          EXAMPLE="${{ steps.header.outputs.example }}"
          SOURCE_FILE="docs/img/${EXAMPLE}-demo.gif"

          if [ -f "$SOURCE_FILE" ]; then
            cp "$SOURCE_FILE" docs/img/header.gif
            echo "✅ Created header.gif from $SOURCE_FILE"
          else
            echo "❌ Source demo file not found: $SOURCE_FILE"
            exit 1
          fi

      - name: Upload demo artifacts (always upload regardless of changes)
        uses: actions/upload-artifact@v4
        with:
          name: demo-gifs-${{ github.run_id }}
          path: docs/img/*.gif
          retention-days: 30

      - name: Upload demo to orphan branch and prepare preview
        if: steps.context.outputs.is_pr == 'true'
        id: demo_preview
        run: |
          if [ -f "docs/img/header.gif" ]; then
            echo "🔄 Uploading header.gif to demo-images branch..."
            
            FILE_SIZE=$(stat -f%z "docs/img/header.gif" 2>/dev/null || stat -c%s "docs/img/header.gif")
            echo "Header GIF size: ${FILE_SIZE} bytes"
            
            # Configure git
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            # Save current state and get commit SHA (safer than branch name with slashes)
            CURRENT_SHA="${{ github.sha }}"
            CURRENT_BRANCH="${{ github.head_ref || github.ref_name }}"
            git add . && git stash || true
            
            # Create or switch to demo-images orphan branch
            if git ls-remote --heads origin demo-images | grep -q demo-images; then
              echo "📁 Switching to existing demo-images branch"
              git fetch origin demo-images
              git checkout demo-images
            else
              echo "📁 Creating new demo-images orphan branch"
              git checkout --orphan demo-images
              git rm -rf . 2>/dev/null || true
              echo "# Demo Images Branch" > README.md
              echo "This branch contains demo images for PR previews." >> README.md
              git add README.md
              git commit -m "Initialize demo-images branch"
            fi
            
             # Copy the demo image with deterministic name using a temp directory
             PR_IMAGE="${{ github.sha }}-header.gif"
             
             # Create a temporary directory to avoid polluting orphan branch
             mkdir -p /tmp/header-extract
             git checkout "$CURRENT_SHA" -- docs/img/header.gif
             mv docs/img/header.gif /tmp/header-extract/
             rm -rf docs/  # Remove entire docs directory from orphan branch
             
             # Copy from temp location to final name
             cp /tmp/header-extract/header.gif "$PR_IMAGE"
             rm -rf /tmp/header-extract
            
            # Add and commit ONLY the PR-specific image
            git add "$PR_IMAGE"
            if git commit -m "Add demo image for PR #${{ github.event.pull_request.number }}"; then
              echo "📷 Added new demo image"
            else
              echo "📷 Demo image unchanged"
            fi
            
            # Push to demo-images branch
            if git push origin demo-images; then
              # Construct the raw URL for inline display
              IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/demo-images/$PR_IMAGE"
              PREVIEW_CONTENT="<img src=\"$IMAGE_URL\" alt=\"Demo GIF\" width=\"100%\">"
              echo "✅ Uploaded to demo-images branch: $PR_IMAGE"
              echo "🔗 Image URL: $IMAGE_URL"
            else
              echo "❌ Failed to push to demo-images branch"
              PREVIEW_CONTENT="❌ Failed to upload demo image to branch"
            fi
            
            # Switch back to original branch
            git checkout "$CURRENT_BRANCH"
            git stash pop 2>/dev/null || true
          else
            PREVIEW_CONTENT="❌ Header GIF generation failed"
            echo "❌ No header.gif file found"
          fi

          # Set the preview content using heredoc syntax
          echo "preview_content<<EOF" >> $GITHUB_OUTPUT
          echo "$PREVIEW_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check if header GIF changed (using git)
        id: check_changes
        run: |
          # Use git to detect changes - much cleaner!
          if git diff --quiet docs/img/header.gif; then
            echo "demo_changed=false" >> $GITHUB_OUTPUT
            echo "✅ Header GIF unchanged"
          else
            echo "demo_changed=true" >> $GITHUB_OUTPUT
            echo "✅ Header GIF has changed"
            
            # Show what changed for debugging
            echo "📊 Git status:"
            git status --porcelain docs/img/header.gif
          fi

      - name: Handle release-please with demo changes (fail build)
        if: steps.context.outputs.is_release_please == 'true' && steps.context.outputs.is_pr == 'true' && steps.check_changes.outputs.demo_changed == 'true'
        run: |
          echo "❌ ERROR: Demo GIF has changed in release-please PR!"
          echo "Demo changes should not be included in release PRs."
          echo "Please update the demo in a separate PR before the release."
          exit 1

      - name: Find existing demo comment
        if: steps.context.outputs.is_pr == 'true' && steps.context.outputs.is_release_please == 'false'
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Header Demo MP4'

      - name: Comment on demo changes (changed)
        if: steps.context.outputs.is_pr == 'true' && steps.context.outputs.is_release_please == 'false' && steps.check_changes.outputs.demo_changed == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## ⚠️ Header Demo GIF Changed - Review Required

            This PR includes changes that affect the demo GIF output. 

            **Please review the generated demo to ensure it accurately represents the library.**

            ### 🎬 Generated Demo Preview:

            ${{ steps.demo_preview.outputs.preview_content }}

            ### Changes Detected:
            - 🎬 `docs/img/header.gif` has been modified

            ### Next Steps:
            1. Review the demo GIF preview above
            2. Ensure the demo accurately shows the intended functionality
            3. If the demo looks correct, this is expected and the PR can proceed
            4. If the demo is incorrect, please update the demo configuration in `demos/${{ steps.header.outputs.example }}.tape`

            <details>
            <summary>🔍 Technical Details</summary>

            The demo was generated from commit [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) using:
            - VHS tape file: [`demos/${{ steps.header.outputs.example }}.tape`](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/demos/${{ steps.header.outputs.example }}.tape)
            - Example: [`examples/${{ steps.header.outputs.example }}.js`](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/examples/${{ steps.header.outputs.example }}.js)
            - Docker image: Built from [`demos/Dockerfile`](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/demos/Dockerfile)

            </details>
          reactions: 'eyes'

      - name: Comment on demo changes (stable)
        if: steps.context.outputs.is_pr == 'true' && steps.context.outputs.is_release_please == 'false' && steps.check_changes.outputs.demo_changed == 'false'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## ✅ Header Demo GIF Reviewed and Stable

            The demo GIF is now stable and matches the current functionality.

            ### Status:
            - 🎬 `docs/img/header.gif` is up-to-date
            - ✅ No further demo review required for this PR

            *This comment will be updated if demo changes are detected in future commits.*
          reactions: 'hooray'

      - name: Commit demo changes (normal commits to main only)
        if: |
          steps.context.outputs.is_pr == 'false' && 
          steps.check_changes.outputs.demo_changed == 'true' && 
          (
            steps.context.outputs.is_release_please == 'false' ||
            github.event.inputs.commit_updates == 'true'
          )
        run: |
          echo "🚀 Committing demo changes..."

          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Retry logic for potential conflicts
          max_retries=3
          retry_count=0

          while [ $retry_count -lt $max_retries ]; do
            echo "Attempt $((retry_count + 1)) of $max_retries"
            
            # Fetch latest changes
            git fetch origin main
            git reset --hard origin/main
            
            # Regenerate demo to ensure we have latest
            npm run demo:generate:basic
            
            # Add and commit
            git add docs/img/*.gif
            
            if git diff --cached --quiet; then
              echo "No changes to commit after regeneration"
              break
            fi
            
            if git commit --no-gpg-sign -m "docs: Update demo MP4s [skip ci]"; then
              if git push; then
                echo "✅ Successfully committed and pushed demo changes"
                break
              else
                echo "⚠️ Push failed, retrying..."
                retry_count=$((retry_count + 1))
                sleep $((retry_count * 2))  # Exponential backoff
              fi
            else
              echo "❌ Commit failed"
              break
            fi
          done

          if [ $retry_count -eq $max_retries ]; then
            echo "❌ Failed to commit after $max_retries attempts"
            exit 1
          fi

      - name: Summary
        run: |
          echo "## 📊 Demo Generation Summary"
          echo "- Event: ${{ github.event_name }}"
          echo "- Demo changed: ${{ steps.check_changes.outputs.demo_changed }}"
          echo "- Is PR: ${{ steps.context.outputs.is_pr }}"
          echo "- Is release-please: ${{ steps.context.outputs.is_release_please }}"
