name: Generate Demo GIFs

on:
  push:
    paths: 
      - 'examples/**'
      - 'demos/**'
      - 'Dockerfile'
      - '.github/workflows/generate-demos.yml'
  workflow_dispatch:
    inputs:
      force_regenerate:
        description: 'Force regenerate all demos'
        required: false
        default: 'false'

jobs:
  generate-demos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create output directory
        run: mkdir -p docs/img
      
      - name: Generate basic demo GIF
        run: npm run demo:generate:basic
      
      - name: List generated files
        run: |
          echo "Generated files:"
          ls -la docs/img/
          if [ -f "docs/img/basic-demo.gif" ]; then
            echo "✅ basic-demo.gif generated successfully"
            echo "File size: $(du -h docs/img/basic-demo.gif)"
          else
            echo "❌ basic-demo.gif was not generated"
            exit 1
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-gifs
          path: docs/img/*.gif
          retention-days: 30
      
      - name: Commit generated GIFs
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/img/*.gif
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit --no-gpg-sign -m "docs: Update demo GIFs [skip ci]"
            git push
          fi 